### ISSUE TITLE
[Fix] Spring cors 오류 수정

### ISSUE THREAD

**Issue by geniusYoo** [morib-in/Jaksim-Server#61]
## ☑️ 어떤 기능인가요?
Spring cors 오류 수정

## ☑️ TODO
- [ ] 헬스체크에 어노테이션 적용 @CrossOrigin
- [ ] Spring Security cors() 설정
- [ ] jwtAuthenticationFilter throw로 에러 안던지고 log
